# Generated by Django 4.1.5 on 2023-02-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('translate', '0004_alter_translation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='input_language',
            field=models.CharField(choices=[('English', 'English'), ('Polish', 'Polish')], default='English',
                                   max_length=7),
            preserve_default=False,
        ),
    ]
